; auto-generated by Sointu, editing not recommended
%define SU_LENGTH_IN_SAMPLES {{.MaxSamples}}
{{- if .Output16Bit}}
%define SU_SAMPLE_SIZE 2
{{- else}}
%define SU_SAMPLE_SIZE 4
{{- end}}
%define SU_CHANNEL_COUNT 2
%define SU_SAMPLE_RATE 44100

%define PM_REMOVE 0x1
%define VK_ESCAPE 0x1B

%define WAVE_FORMAT_IEEE_FLOAT 0x3
%define WHDR_PREPARED 0x2
%define WAVE_MAPPER 0xFFFFFFFF
%define TIME_SAMPLES 0x2

; For win32 messages.
section msg bss
msg:
    resd 1
message:
    resd 7

; Music related data.


; This needs to be extracted manually from the header sointu generates.
%define SAMPLE_COUNT 3663360
%define SAMPLE_RATE 44100

section wavefmt data
wavefmt:
    dw WAVE_FORMAT_IEEE_FLOAT
    dw SU_CHANNEL_COUNT
    dd SAMPLE_RATE 
    dd SAMPLE_SIZE * SAMPLE_RATE * CHANNEL_COUNT
    dw SAMPLE_SIZE * CHANNEL_COUNT
    dw SAMPLE_SIZE * 8
    dw 0

section wavehdr data
wavehdr:
    dd soundbuffer
    dd SAMPLE_COUNT * SAMPLE_SIZE * CHANNEL_COUNT
    times 2 dd 0
    dd WHDR_PREPARED
    times 4 dd 0
wavehdr_end:

section soundbuffer bss
soundbuffer:
    resd SAMPLE_COUNT * SAMPLE_SIZE * CHANNEL_COUNT

section hwaveout bss
hwaveout:
    resd 1

section symbols text
symbols:
    extern _su_render_song@4
{{- if gt (.SampleOffsets | len) 0}}
    extern _su_load_gmdls@4
{{- end}}
    extern _GetAsyncKeyState@4
    extern _PeekMessageA@20
    extern _DispatchMessageA@4
    extern _waveOutOpen@24
    extern _waveOutWrite@12
    
section entry text
    global _mainCRTStartup
_mainCRTStartup:
    push soundbuffer
    call _su_render_song@4