# Run unit tests using CTest and go tests
name: Tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: lukka/get-cmake@v3.18.3
    - uses: actions/setup-go@v2
    - uses: actions/checkout@v2
    - uses: ilammy/setup-nasm@v1.1.0
    - run: /home/runner/nasm/nasm -version
    - name: Running ctests
      env:
        ASM_NASM: /home/runner/nasm/nasm
      run: |
        mkdir build
        cd build
        cmake -GNinja ..
        ninja
        ctest --output-on-failure
    - name: Running go tests
      run: |
        cd go4k
        go test . ./bridge
