set(X86 ON)
set(CRINKLER ON)

# Assembler settings
set(CMAKE_ASM_NASM_FLAGS "-fwin32 -Ox")

# Linker settings
set(CMAKE_ASM_NASM_LINK_EXECUTABLE "<CMAKE_LINKER> <CMAKE_ASM_NASM_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> /out:<TARGET> <LINK_LIBRARIES>")
set(CMAKE_ASM_NASM_LINK_LIBRARY_SUFFIX ".lib")
set(CMAKE_ASM_NASM_LINK_LIBRARY_FLAG "")
set(CMAKE_ASM_NASM_LIBRARY_PATH_FLAG "/libpath:")
set(CMAKE_ASM_NASM_LINK_FLAGS /subsystem:windows /progressgui /compmode:veryslow /HASHTRIES:2400 /ORDERTRIES:20000 /TINYIMPORT /UNSAFEIMPORT /UNALIGNCODE)
